version: '3.7'

services:
  zabbix-all-in-one:
    image: zabbix/zabbix-appliance:6.4-latest
    container_name: zabbix-all-in-one
    ports:
      - "8080:80"       # Interfície web
      - "10051:10051"   # Port de comunicació del servidor
    environment:
      DB_SERVER_HOST: localhost
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - zabbix-data:/var/lib/zabbix
    restart: unless-stopped

volumes:
  zabbix-data:
